### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by smbolton** [ranweiler/liar#13]
Hi Joe!
With both the MIT and ISC licenses in the root directory, but no explanation anywhere, it's unclear what you intend the licensing to be.

**Comment by ranweiler** [comment]
Sorry for the confusion! The license is ISC, and the MIT license is included for the sake of the implementations of `black_box`, which are obtained (via the MIT license) from the `bencher` and upstream Rust `libtest` crates. I'll note Liar's license in the README, and add the license name to `Cargo.toml` (right now I only identify the license file).
